version: '3'
services:
  mysql8:
    image: mysql:8.2
    command:
      - --general-log
    volumes:
      - ./examples/provider:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 23306:3306
